spring:
  mvc:
    throw-exception-if-no-handler-found: true # 找不到url时抛出异常
    static-path-pattern: /statics/**
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: none
  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true

sleeve:
  year-codes: A,B,C,D,E,F,J,H #从2020年开始 A 2020 B 2021 C 2020

